server:
  port: 8080

# Log Level 설정
logging:
  level:
    root: info

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    driver-class-name: org.h2.Driver
    url:
    username: sa
    password:

# RabbitMQ queue, exchange, routing-key 정보
rabbitmq:
  queue.name: sample.queue
  exchange.name: sample.exchange
  routing.key: sample.key